
name: Get Modified Files
  
on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
      
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
      
    - id: exit-if-no-files
      if: ${{ steps.files.outputs.all }} != *"test-modified-files.yml"*
      run: echo 'Modified files do not contain \"test-modified-files.yml\"' && exit 1
        
    - id: post-validation
      run: echo 'test-modified-files.yml was included'
